# Generated by Django 5.2.17 on 2026-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedsysNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(db_index=True, max_length=12, unique=True)),
                ("ds_response", models.CharField(blank=True, max_length=8)),
                ("signature_valid", models.BooleanField()),
                ("raw_merchant_parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
