# Generated by Django 5.2.17 on 2026-09-22 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscar_redsys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RedsysOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(db_index=True, max_length=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("2", "Confirmation"), ("3", "Refund"), ("9", "Cancellation")],
                        max_length=1,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("success", models.BooleanField()),
                ("error_code", models.CharField(blank=True, max_length=16)),
                ("ds_response", models.CharField(blank=True, max_length=8)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_refund_or_cancel", "Can refund or cancel a Redsys payment")],
            },
        ),
    ]
