# Generated by Django 5.2.17 on 2026-10-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscar_redsys", "0002_redsysoperation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redsysnotification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Redsys notification",
                "verbose_name_plural": "Redsys notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="redsysoperation",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_refund_or_cancel", "Can refund or cancel a Redsys payment")],
                "verbose_name": "Redsys operation",
                "verbose_name_plural": "Redsys operations",
            },
        ),
        migrations.AlterField(
            model_name="redsysnotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="redsysnotification",
            name="ds_response",
            field=models.CharField(blank=True, max_length=8, verbose_name="Redsys response code"),
        ),
        migrations.AlterField(
            model_name="redsysnotification",
            name="order_number",
            field=models.CharField(
                db_index=True, max_length=12, unique=True, verbose_name="Order number"
            ),
        ),
        migrations.AlterField(
            model_name="redsysnotification",
            name="raw_merchant_parameters",
            field=models.JSONField(verbose_name="Raw merchant parameters"),
        ),
        migrations.AlterField(
            model_name="redsysnotification",
            name="signature_valid",
            field=models.BooleanField(verbose_name="Signature valid"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="ds_response",
            field=models.CharField(blank=True, max_length=8, verbose_name="Redsys response code"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="error_code",
            field=models.CharField(blank=True, max_length=16, verbose_name="Error code"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="order_number",
            field=models.CharField(db_index=True, max_length=12, verbose_name="Order number"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="raw_response",
            field=models.JSONField(blank=True, null=True, verbose_name="Raw response"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested by",
            ),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="success",
            field=models.BooleanField(verbose_name="Success"),
        ),
        migrations.AlterField(
            model_name="redsysoperation",
            name="transaction_type",
            field=models.CharField(
                choices=[("2", "Confirmation"), ("3", "Refund"), ("9", "Cancellation")],
                max_length=1,
                verbose_name="Transaction type",
            ),
        ),
    ]
